version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data 
  api:
    build: .
    command: ["air"]
    ports:
      - "7000:7000"
    volumes:
      - ./:/app
    depends_on:
      - db 
    env_file:
      - .env
volumes:
  db: